console.log('Hello,')
console.log('Here is the Mariners batting order:')
console.log('1. Jean Segura')
console.log('2. Mitch Haniger')
console.log('3. Robinson Cano')
console.log('4. Nelson Cruz')
console.log('5. Kyle Seager')
console.log('6. Danny Valencia')
console.log('7. Mike Zunino')
console.log('8. Jarrod Dyson')
console.log('9. Leonys Martin')